version: '3.8'

name: mogak_us_test

services:
  test:
    build: .
    command: sh -c "poetry run python manage.py test main.tests"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: test_db_name
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: mogak_us.settings.test
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db_name
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
