version: '3.8'

services:
  web:
    build: .
    command: sh -c "poetry run python manage.py runserver 0.0.0.0:8000 & npm run dev"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test:
    build: .
    command: sh -c "poetry run python manage.py test --settings=mogak_us.settings.test"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: test_db_name
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
