# Generated by Django 5.1.5 on 2025-02-08 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_meetup_attendance_mogakuser_meetups"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_meetups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
